<a href="https://colab.research.google.com/github/crislmfroes/tensorflow-colab/blob/master/camadas_personalizadas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import tensorflow as tf
from tensorflow import keras
tf.enable_eager_execution()

In [0]:
layer = keras.layers.Dense(100)

In [0]:
layer_input_specified = keras.layers.Dense(10, input_shape=[None, 5])

In [7]:
layer(tf.zeros([10, 5]))

<tf.Tensor: id=31, shape=(10, 100), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 

In [8]:
layer_input_specified(tf.zeros([10, 5]))

<tf.Tensor: id=63, shape=(10, 10), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

In [9]:
layer.variables

[<tf.Variable 'dense_2/kernel:0' shape=(5, 100) dtype=float32, numpy=
 array([[ 3.24629396e-02, -1.52373463e-02, -1.37580901e-01,
          2.31784150e-01, -2.14790776e-01,  2.08890006e-01,
          1.32480308e-01, -2.27336928e-01, -2.16438621e-01,
          2.38843009e-01,  2.12010786e-01,  1.21750250e-01,
         -1.40138984e-01, -1.12533927e-01, -1.31414503e-01,
         -1.74150765e-01, -1.79879248e-01, -1.09136015e-01,
          1.73193172e-01,  7.50428885e-02,  1.68354362e-02,
         -5.15181422e-02, -5.57835549e-02,  8.46828371e-02,
         -2.09838778e-01, -3.47201526e-03,  1.39658898e-02,
          1.68724403e-01, -2.08643645e-01, -2.26349980e-01,
          1.57002404e-01, -1.01018056e-01,  1.04615614e-01,
         -6.77276701e-02,  2.88269669e-02, -1.84133932e-01,
         -1.65082157e-01,  4.54611629e-02, -5.01531661e-02,
          1.69554219e-01,  9.06201452e-02, -2.34063342e-01,
          1.55428246e-01, -1.39427707e-01, -3.65060866e-02,
          6.74386322e-03,  1.4

In [10]:
layer.kernel, layer.bias

(<tf.Variable 'dense_2/kernel:0' shape=(5, 100) dtype=float32, numpy=
 array([[ 3.24629396e-02, -1.52373463e-02, -1.37580901e-01,
          2.31784150e-01, -2.14790776e-01,  2.08890006e-01,
          1.32480308e-01, -2.27336928e-01, -2.16438621e-01,
          2.38843009e-01,  2.12010786e-01,  1.21750250e-01,
         -1.40138984e-01, -1.12533927e-01, -1.31414503e-01,
         -1.74150765e-01, -1.79879248e-01, -1.09136015e-01,
          1.73193172e-01,  7.50428885e-02,  1.68354362e-02,
         -5.15181422e-02, -5.57835549e-02,  8.46828371e-02,
         -2.09838778e-01, -3.47201526e-03,  1.39658898e-02,
          1.68724403e-01, -2.08643645e-01, -2.26349980e-01,
          1.57002404e-01, -1.01018056e-01,  1.04615614e-01,
         -6.77276701e-02,  2.88269669e-02, -1.84133932e-01,
         -1.65082157e-01,  4.54611629e-02, -5.01531661e-02,
          1.69554219e-01,  9.06201452e-02, -2.34063342e-01,
          1.55428246e-01, -1.39427707e-01, -3.65060866e-02,
          6.74386322e-03,  1.4

In [0]:
class MyDenseLayer(keras.layers.Layer):
  def __init__(self, num_outputs):
    super(MyDenseLayer, self).__init__()
    self.num_outputs = num_outputs
  def build(self, input_shape):
    self.kernel = self.add_variable('kernal', shape=[int(input_shape[-1]), self.num_outputs])
  def call(self, x):
    return tf.matmul(x, self.kernel)

In [13]:
my_layer = MyDenseLayer(10)
print(my_layer(tf.zeros([10, 5])))
print(my_layer.variables)

tf.Tensor(
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]], shape=(10, 10), dtype=float32)
[<tf.Variable 'my_dense_layer_1/kernal:0' shape=(5, 10) dtype=float32, numpy=
array([[ 0.17097801,  0.31673503, -0.01885921, -0.05127949,  0.10431594,
        -0.17927563, -0.28296173, -0.04638398, -0.59037375,  0.15208882],
       [-0.29315174,  0.3236395 ,  0.0698241 ,  0.56008774,  0.61570424,
        -0.35041332,  0.46438342, -0.45382422,  0.03138238,  0.31591278],
       [ 0.23787636,  0.4420312 ,  0.42258888,  0.4512747 ,  0.2513708 ,
        -0.20357892, -0.06644601, -0.33391517,  0.12170583, -0.02373725],
       [ 0.56857497, -0.15441638,  0.46772164,  0.21100545, -0.39596975,
        -0.20717767,  0.62492794, 

In [0]:
class ResNetIdentityBlock(keras.Model):
  def __init__(self, kernel_size, filters):
    super(ResNetIdentityBlock, self).__init__()
    filters1, filters2, filters3 = filters
    self.conv2a = keras.layers.Conv2D(filters1, (1, 1))
    self.bn2a = keras.layers.BatchNormalization()
    self.conv2b = keras.layers.Conv2D(filters2, kernel_size, padding='same')
    self.bn2b = keras.layers.BatchNormalization()
    self.conv2c = keras.layers.Conv2D(filters3, (1, 1))
    self.bn2c = keras.layers.BatchNormalization()
  def call(self, input_tensor, training=False):
    x = self.conv2a(input_tensor)
    x = self.bn2a(x, training=training)
    x = tf.nn.relu(x)
    x = self.conv2b(x)
    x = self.bn2b(x, training=training)
    x = tf.nn.relu(x)
    x = self.conv2c(x)
    x = self.bn2c(x, training=training)
    x = tf.nn.relu(x)
    x += input_tensor
    return tf.nn.relu(x)

In [18]:
block = ResNetIdentityBlock(1, [1, 2, 3])
print(block(tf.zeros([1, 2, 3, 3])))
print([x.name for x in block.variables])

tf.Tensor(
[[[[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]

  [[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]]], shape=(1, 2, 3, 3), dtype=float32)
['res_net_identity_block_1/conv2d_4/kernel:0', 'res_net_identity_block_1/conv2d_4/bias:0', 'res_net_identity_block_1/batch_normalization_3/gamma:0', 'res_net_identity_block_1/batch_normalization_3/beta:0', 'res_net_identity_block_1/conv2d_5/kernel:0', 'res_net_identity_block_1/conv2d_5/bias:0', 'res_net_identity_block_1/batch_normalization_4/gamma:0', 'res_net_identity_block_1/batch_normalization_4/beta:0', 'res_net_identity_block_1/conv2d_6/kernel:0', 'res_net_identity_block_1/conv2d_6/bias:0', 'res_net_identity_block_1/batch_normalization_5/gamma:0', 'res_net_identity_block_1/batch_normalization_5/beta:0', 'res_net_identity_block_1/batch_normalization_3/moving_mean:0', 'res_net_identity_block_1/batch_normalization_3/moving_variance:0', 'res_net_identity_block_1/batch_normalization_4/moving_mean:0', 'res_net_identity_block_1/batch_normalization_4/movi

In [0]:
my_seq = keras.Sequential([
    keras.layers.Conv2D(1, (1, 1)),
    keras.layers.BatchNormalization(),
    keras.layers.Conv2D(2, 1, padding='same'),
    keras.layers.BatchNormalization(),
    keras.layers.Conv2D(3, (1, 1)),
    keras.layers.BatchNormalization()
])

In [20]:
my_seq(tf.zeros([1, 2, 3, 3]))

<tf.Tensor: id=835, shape=(1, 2, 3, 3), dtype=float32, numpy=
array([[[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]]], dtype=float32)>

In [0]:
my_other_seq = keras.Sequential([
    my_seq,
    keras.layers.Dense(10, activation='softmax')
])

In [0]:
my_other_seq.compile(optimizer=tf.train.AdamOptimizer(learning_rate=0.001), loss='categorical_crossentropy', metrics=['accuracy'])

In [33]:
my_other_seq(tf.zeros([1, 2, 3, 3]))

<tf.Tensor: id=947, shape=(1, 2, 3, 10), dtype=float32, numpy=
array([[[[0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1],
         [0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1],
         [0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1]],

        [[0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1],
         [0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1],
         [0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1]]]],
      dtype=float32)>

In [34]:
my_other_seq.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
sequential (Sequential)      multiple                  41        
_________________________________________________________________
dense_4 (Dense)              multiple                  40        
Total params: 81
Trainable params: 69
Non-trainable params: 12
_________________________________________________________________


In [0]:
#@title Apache 2.0 License
#Copyright 2018 Alphabet, Inc
#
#Licensed under the Apache License, Version 2.0 (the "License");
#you may not use this file except in compliance with the License.
#You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
#Unless required by applicable law or agreed to in writing, software
#distributed under the License is distributed on an "AS IS" BASIS,
#WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#See the License for the specific language governing permissions and
#limitations under the License.