<a href="https://colab.research.google.com/github/crislmfroes/tensorflow-colab/blob/master/eager_basico.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import tensorflow as tf
import numpy as np
import tempfile

tf.enable_eager_execution()

In [0]:
print(tf.add(1, 2))
print(tf.add([1, 2], [3, 4]))
print(tf.square(5))
print(tf.reduce_sum([1, 2, 3]))
print(tf.encode_base64('Olá mundo!'))
print(tf.square(2) + tf.square(3))

tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor([4 6], shape=(2,), dtype=int32)
tf.Tensor(25, shape=(), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)
tf.Tensor(b'T2zDoSBtdW5kbyE', shape=(), dtype=string)
tf.Tensor(13, shape=(), dtype=int32)


In [0]:
x = tf.matmul([[4]], [[2, 3]])
print(x)
print(x.shape)
print(x.dtype)

tf.Tensor([[ 8 12]], shape=(1, 2), dtype=int32)
(1, 2)
<dtype: 'int32'>


In [0]:
array = np.ones([3, 3])
print('Operações Tensorflow convertem vetores NumPy para tensores automaticamente')
tensor = tf.multiply(array, 42)
print(tensor)
print('E operações NumPy convertem tensores Tensorflow para vetores NumPy automaticamente')
print(np.add(tensor, 1))
print('O método .numpy() converte explicitamente um tensor para um vetor numpy')
print(tensor.numpy())

Operações Tensorflow convertem vetores NumPy para tensores automaticamente
tf.Tensor(
[[42. 42. 42.]
 [42. 42. 42.]
 [42. 42. 42.]], shape=(3, 3), dtype=float64)
E operações NumPy convertem tensores Tensorflow para vetores NumPy automaticamente
[[43. 43. 43.]
 [43. 43. 43.]
 [43. 43. 43.]]
O método .numpy() converte explicitamente um tensor para um vetor numpy
[[42. 42. 42.]
 [42. 42. 42.]
 [42. 42. 42.]]


In [0]:
x = tf.random_uniform([3, 3])
print('GPU se encontra disponível: ')
print(tf.test.is_gpu_available())
print('O tensor se encontra na GPU #0: ')
print(x.device.endswith('GPU:0'))

GPU se encontra disponível: 
True
O tensor se encontra na GPU #0: 
True


In [0]:
def time_matmul(x):
  %timeit tf.matmul(x, x)

In [0]:
print('Na CPU:')
with tf.device('CPU:0'):
  x = tf.random_uniform([100, 100])
  assert x.device.endswith('CPU:0')
  time_matmul(x)
if tf.test.is_gpu_available():
  print('Na GPU:')
  with tf.device('GPU:0'):
    x = tf.random_uniform([100, 100])
    assert x.device.endswith('GPU:0')
    time_matmul(x)

Na CPU:
10000 loops, best of 3: 66.5 µs per loop
Na GPU:
The slowest run took 3629.13 times longer than the fastest. This could mean that an intermediate result is being cached.
1 loop, best of 3: 59.3 µs per loop


In [0]:
ds_tensor = tf.data.Dataset.from_tensor_slices([1, 2, 3, 4, 5, 6])
_, filename = tempfile.mkstemp()
with open(filename, 'w') as f:
  f.write("""Linha 1
Linha 2
Linha 3
  """)
ds_file = tf.data.TextLineDataset(filename)

In [0]:
ds_tensor = ds_tensor.map(tf.square).shuffle(2).batch(2)
ds_file = ds_file.batch(2)

In [0]:
print('Elementos de ds_tensor:')
for x in ds_tensor:
  print(x)
print('\nElementos em ds_file:')
for x in ds_file:
  print(x)

Elementos de ds_tensor:
tf.Tensor([1 9], shape=(2,), dtype=int32)
tf.Tensor([16  4], shape=(2,), dtype=int32)
tf.Tensor([36 25], shape=(2,), dtype=int32)

Elementos em ds_file:
tf.Tensor([b'Linha 1' b'Linha 2'], shape=(2,), dtype=string)
tf.Tensor([b'Linha 3' b'  '], shape=(2,), dtype=string)


In [0]:
#@title Apache 2.0 License
#Copyright 2018 Alphabet, Inc
#
#Licensed under the Apache License, Version 2.0 (the "License");
#you may not use this file except in compliance with the License.
#You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
#Unless required by applicable law or agreed to in writing, software
#distributed under the License is distributed on an "AS IS" BASIS,
#WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#See the License for the specific language governing permissions and
#limitations under the License.