<a href="https://colab.research.google.com/github/crislmfroes/tensorflow-colab/blob/master/gradientes_diferenciacao_automatica.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import tensorflow as tf
tf.enable_eager_execution()

In [0]:
x = tf.ones((2, 2))
with tf.GradientTape() as t:
  t.watch(x)
  y = tf.reduce_sum(x)
  z = tf.multiply(y, y)
  
dz_dx = t.gradient(z, x)
for i in [0, 1]:
  for j in [0, 1]:
    assert dz_dx[i][j].numpy() == 8.0

In [0]:
with tf.GradientTape() as t:
  t.watch(x)
  y = tf.reduce_sum(x)
  z = tf.multiply(y, y)
dz_dy = t.gradient(z, y)
assert dz_dy.numpy() == 8.0

In [12]:
x = tf.ones([3, 3, 3])
with tf.GradientTape(persistent=True) as t:
  t.watch(x)
  y = tf.reduce_sum(x)
  z = tf.multiply(y, y)
dz_dx = t.gradient(z, x)
dz_dy = t.gradient(z, y)

print(dz_dx)
print(dz_dy)

del t


tf.Tensor(
[[[54. 54. 54.]
  [54. 54. 54.]
  [54. 54. 54.]]

 [[54. 54. 54.]
  [54. 54. 54.]
  [54. 54. 54.]]

 [[54. 54. 54.]
  [54. 54. 54.]
  [54. 54. 54.]]], shape=(3, 3, 3), dtype=float32)
tf.Tensor(54.0, shape=(), dtype=float32)


In [0]:
def f(x, y):
  output = 1.0
  for i in range(y):
    if i > 1 and i < 5:
      output = tf.multiply(output, x)
  return output

In [0]:
def grad(x, y):
  with tf.GradientTape() as t:
    t.watch(x)
    out = f(x, y)
  return t.gradient(out, x)

In [0]:
x = tf.convert_to_tensor(2.0)
assert grad(x, 6).numpy() == 12
assert grad(x, 5).numpy() == 12
assert grad(x, 4).numpy() == 4

In [0]:
x = tf.Variable(1.0)

with tf.GradientTape() as t:
  with tf.GradientTape() as t2:
    y = x * x * x
  dy_dx = t2.gradient(y, x)
d2y_dx2 = t.gradient(dy_dx, x)

assert dy_dx.numpy() == 3.0
assert d2y_dx2.numpy() == 6.0    

In [0]:
#@title Apache 2.0 License
#Copyright 2018 Alphabet, Inc
#
#Licensed under the Apache License, Version 2.0 (the "License");
#you may not use this file except in compliance with the License.
#You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
#Unless required by applicable law or agreed to in writing, software
#distributed under the License is distributed on an "AS IS" BASIS,
#WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#See the License for the specific language governing permissions and
#limitations under the License.